### ISSUE TITLE
Error during setup of component transmission

### ISSUE THREAD

**Issue by Naesstrom** [Naesstrom/home_assistant#2]
Error during setup of component transmission
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 154, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/transmission/__init__.py", line 57, in setup
    host = config[DOMAIN][CONF_HOST]
KeyError: 'transmission'

**Comment by Naesstrom** [comment]
Unable to set up dependencies of transmission.sensor. Setup failed for dependencies: transmission

**Comment by Naesstrom** [comment]
breaking change made in 0.87. Now fixed
